[package]
name = "site"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
yew = { version = "0.20.0", features = ["csr"] }
wasm-bindgen = "0.2"
yew-router = "0.17.0"

[dependencies.web-sys]
version = "0.3"
features = [
]
